### ISSUE TITLE
Any modifications using this mod?

### ISSUE THREAD

**Issue by Binero** [BlazeCodeNet/VanillifyMod#1]
Are there any modifications using this mod? I am thinking of using this to make my own modification, but I would like to see what others have done.

**Comment by BlazeCodeNet** [comment]
I havent heard of any public ones. Ill add a few tonight to my public repositories and let you know when its done. I appreciate the interest!

**Comment by BlazeCodeNet** [comment]
Made a public mod that uses the ServerBlock and ServerBlockItem part of Vanillify. Its called "JumpVaders". You're free to look at the source code on my profile.

Ive also made a official list of mods that use vanillify with instructions on how to add yours to the list on the page. You can find that [here](https://github.com/BlazeCodeNet/VanillifyMod/wiki/Mods-made-using-Vanillify#here-is-a-list-of-mods-made-using-vanillify)
