### ISSUE TITLE
Maven server down?

### ISSUE THREAD

**Issue by thetek42** [BlazeCodeNet/VanillifyMod#3]
I wanted to set up Vanillify to play around with it for a bit, but after adding the Maven repo (`maven.blazecode.net`) and the dependency as specified in the Wiki, I get the following error when trying to run the mod:

```
FAILURE: Build failed with an exception.
[...]
> Could not resolve net.blazecode:vanillify:1.3.54.
[...]
> Connect to maven.blazecode.net:443 [maven.blazecode.net/173.27.176.169] failed: Connect timed out
```

When opening the URL in a browser, the connection times out as well.

Also, as a side note, there is a typo in the home page of the Wiki – `${project.vaillify_version}` – the n in Vanillify is missing.

**Comment by BlazeCodeNet** [comment]
Oof. Im on vacation actually until October 4th. I can confirm that both things you said are true, but I dont have the ability to fix it until that date. Ill do so as soon as I possibly can though, and I appreciate your interest in this project!

**Comment by thetek42** [comment]
No problem. Is there a way I can use this without the maven server? I'm guessing that I would just need to put the compiled .jar file somewhere, but I don't know where exactly.

**Comment by BlazeCodeNet** [comment]
> No problem. Is there a way I can use this without the maven server? I'm guessing that I would just need to put the compiled .jar file somewhere, but I don't know where exactly.

I dont personally know how to do a manual jar reference in java. There is a way to use the modrinth maven since its uploaded there. Try asking in the modrinth discord?

Again, im very sorry about not being much help right now!

**Comment by thetek42** [comment]
Figured it out. The compiled .jar has to go into `build/loom-cache`.

Edit: When adding the .jar to that folder, the mod will be accepted as a regular mod and Gradle will stop complaining about not having access to it. However, it cannot be used for development as it gets loaded as a normal mod and not as a dependency of the project.

**Comment by BlazeCodeNet** [comment]
> Figured it out. The compiled .jar has to go into `build/loom-cache`.
> 
> Edit: When adding the .jar to that folder, the mod will be accepted as a regular mod and Gradle will stop complaining about not having access to it. However, it cannot be used for development as it gets loaded as a normal mod and not as a dependency of the project.

Oof, I am so sorry. Unexpected things kept popping up IRL and im just getting free time today to fix that Maven server. Im certain you've moved onto other projects by now lol, but ill post this here just in case there are others that had issues with the maven. Sincerely do appreciate your interest in the project, and once again I do apologize for the monstrous delay before it was fixed.

All should be operational now.
