### ISSUE TITLE
Difference between Polymer and this mod?

### ISSUE THREAD

**Issue by gazpachoking** [BlazeCodeNet/VanillifyMod#5]
Just curious, seems the same goals as polymer. https://modrinth.com/mod/polymer Maybe add this question to your FAQ or the pinned issue as well?

**Comment by BlazeCodeNet** [comment]
Copy of #2 

This mod is on temporary hold until I get more free time. But a lot of the stuff mentioned in #2 apply here. Polymer is targeting modpacks while Vanillify is suppose to be more of a "Server-Side Library" that allows modded items server-side without any other targeted environments. Its still extremely early, but I eventually intend it to be a fully-fledged API similar to Spigot/Bukkit but within the FabricMC Ecosystem of course.

**Comment by gazpachoking** [comment]
Hmm, I think the goal might be more similar than you think. Polymer isn't for modpack devs or players, it's also a serverside library mods can use if they want to support vanilla clients. Perhaps some combining of efforts might be in order, or at least some closer inspection of that mod. It also has your 2 future plans bullet points implemented already.

**Comment by BlazeCodeNet** [comment]
> Hmm, I think the goal might be more similar than you think. Polymer isn't for modpack devs or players, it's also a serverside library mods can use if they want to support vanilla clients. Perhaps some combining of efforts might be in order, or at least some closer inspection of that mod. It also has your 2 future plans bullet points implemented already.

Ive had some issues with the author of that mod personally in the past, so this one was started with the intent to implement features that polymer was missing. I guess you're somewhat right: Polymer does do a lot of the stuff now that Vanillify was planning to do. Im not really sure what to do with the project currently.
